
USE Sk84TEC_SQL;
SET TRANSACTION 
ISOLATION LEVEL READ COMMITTED;
BEGIN TRAN

	SELECT * FROM Usuario
	WHERE Usuario.IdUsuario = 56;

	SELECT * FROM Usuario
	WHERE Usuario.IdUsuario = 56;

COMMIT TRAN;